version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: xphunt-db
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    restart: unless-stopped

  app:
    build: .
    container_name: xphunt-app
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/$POSTGRES_DB
      SPRING_DATASOURCE_USERNAME: $POSTGRES_USER
      SPRING_DATASOURCE_PASSWORD: $POSTGRES_PASSWORD
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: $APP_JWT_SECRET
      JWT_EXPIRATION: $APP_JWT_EXPIRATION-MS
    restart: on-failure


volumes:
  db-data:
