version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: xphunt-db
    environment:
      - POSTGRES_USER=${postgres.username}
      - POSTGRES_PASSWORD=${postgres.password}
      - POSTGRES_DB=${postgres.dbname}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    restart: unless-stopped

  app:
    build: .
    container_name: xphunt-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      -SPRING_DATASOURCE_URL : ${spring.datasource.url}
      -SPRING_DATASOURCE_USERNAME : ${postgres}
      -SPRING_DATASOURCE_PASSWORD : ${sergtsoP@321}
      -SPRING_JPA_HIBERNATE_DDL_AUTO : update

      -JWT_SECRET : ${app.jwt.secret}
      -JWT_EXPIRATION : ${app.jwt.expiration-ms}
    restart: on-failure

volumes:
  db-data:
