version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: xphunt-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=xphunt
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    restart: unless-stopped

  app:
    build: .
    container_name: xphunt-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      -SPRING_DATASOURCE_URL : jdbc:postgresql://db:5432/xphunt
      -SPRING_DATASOURCE_USERNAME : postgres
      -SPRING_DATASOURCE_PASSWORD : postgres
      -SPRING_JPA_HIBERNATE_DDL_AUTO : update

      -JWT_SECRET : bXktc3VwZXItc2VjcmV0LWtleS1mb3Itand0LXNpZ25pbmctdGhhdC1pcy1sb25nLWVub3VnaA==
      -JWT_EXPIRATION : 3600000
    restart: on-failure

volumes:
  db-data:
